### ISSUE TITLE
Matching algorithm associating Mappings to Hosts is bogus

### ISSUE THREAD

**Issue by AdaptiveMrBrown** [emissary-ingress/emissary#4791]
**Describe the bug**

For mappings that have a `host` field defined with a port, Emissary will be unable to associate the
mapping with any `Host` with a `hostname` other that `'*'`. We suspect the matching algorithm to be
bogus.

**To Reproduce**

Start by following the [getting started](https://www.getambassador.io/docs/emissary/latest/tutorials/getting-started)
and stop at step 3. Apply this `Mapping` instead:

```shell
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  host: "quote.local:8080" # <-- modified
  prefix: /backend/
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"
EOF
```

Then forward the Emissary service port 80 to 8080:

```shell
kubectl port-forward -n emissary "svc/emissary-ingress" 8080:80
```

Try to reach the service with `curl`:

```shell
# Works
curl -v -H 'Host: quote.local:8080' 127.0.0.1:8080/backend/

# Doesn't work, code 404
curl -v -H 'Host: quote.local' 127.0.0.1:8080/backend/
```

**Note:** we'll re-use these curl commands later

This is actually problematic since `hostname` should only be the name of the host without a port number.
There might be a `port` field missing in the `Mapping` CRD `v3alpha1`.

Now create a `Host`:

```shell
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: minimal-host
  namespace: emissary
spec:
  hostname: '*' # <-- look here
  requestPolicy:
    insecure:
      action: Route
      additionalPort: -1
EOF
```

Both curl commands mentioned before still work in the same way.

Let's update this host configuration with a domain name:

```shell
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: minimal-host
  namespace: emissary
spec:
  hostname: '*.local' # <-- look here
  requestPolicy:
    insecure:
      action: Route
      additionalPort: -1
EOF
```

With this configuration, we can't reach the quote service at all. We can sort of reach it if we update the `Mapping`:

```shell
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  host: "quote.local" # <-- look here
  prefix: /backend/
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"
EOF
```

And if we try our previous `curl` commands:

```shell
# Now this doesn't works, code 404
curl -v -H 'Host: quote.local:8080' 127.0.0.1:8080/backend/

# And this works
curl -v -H 'Host: quote.local' 127.0.0.1:8080/backend/
```

Since HTTP clients will always set the `Host` header to \<hostname\>:\<port\> unless we override it,
the quote service is just unreachable if our ingress is on any other port than 80 or 443.

**Expected behavior**

Given the following `Mapping`:

```shell
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  host: "quote.local:8080" # The port number should probably be in its own field.
  prefix: /backend/
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"
EOF
```

And given the following `Host`:

```shell
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: minimal-host
  namespace: emissary
spec:
  hostname: '*.local' # This might not be precise enough in all cases. Switching to mappingSelector would solve it though.
  requestPolicy:
    insecure:
      action: Route
      additionalPort: -1
EOF
```

We expect this to hit the mapped service:

```shell
curl -v -H 'Host: quote.local:8080' 127.0.0.1:8080/backend/
```

**Versions**

* Emissary 3.4.0 from Helm chart 8.4.0
* Minikube v1.28.0 launching Kubernetes 1.25.3 with the Docker driver

**Comment by cindymullins-dw** [comment]
Hi @AdaptiveMrBrown , does this config include a Listener from the QuickStart?  I think there's an issue with trying to assign the port directly to the host.

**Comment by AdaptiveMrBrown** [comment]
Hi @cindymullins-dw , I definitely applied this listener when I did my tests (copy/pasted from the quickstart):

```yaml
kubectl apply -f - <<EOF
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8080
  namespace: emissary
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
EOF```

**Comment by cindymullins-dw** [comment]
Looks like this issue has been addressed.

**Comment by AdaptiveMrBrown** [comment]
@cindymullins-dw , I can still reproduce the issue by following the instructions I provided when I opened the issue. I just tested it right now with the emissary-ingress helm chart 8.5.1.
